export const catDescription = [
  "Our beloved grey and white Persian cat, has been missing since yesterday evening. He was last seen near our house on Oak Street. My pet is a large, friendly cat with bright green eyes and a distinctive fluffy tail. He is very affectionate and responds well to his name. He is microchipped, so if found, please contact us immediately so we can be reunited with our furry friend. We miss him dearly and are offering a reward for his safe return. Thank you for your help in finding him.",
  "He's a handsome orange tabby with black stripes and big, bright eyes. Max is about 4 years old and has a distinctive black spot on his left paw. He was last seen in the neighborhood around our home, near the park. He is an indoor/outdoor cat and is very friendly, but can be a little skittish around new people. He loves to play with his toys and cuddle up in cozy blankets. He is wearing a red collar with a bell and a tag with our contact information. If you see Max or have any information on his whereabouts, please contact us as soon as possible. We're offering a reward for his safe return. We miss him terribly and just want him to come home safely.",
  "He's a ginger tabby with striking green eyes, and is about 3 years old. He was last seen near the park in the downtown area of town. He is very friendly and loves to be petted, but can be skittish around loud noises and unfamiliar surroundings. If you see him or have any information on his whereabouts, please contact us as soon as possible. We miss him terribly and just want him to come home safely. He is microchipped and wears a blue collar with a silver tag containing our contact information.",
  "He's a black and white tuxedo cat with big yellow eyes, and is about 1 year old. He was last seen in the neighborhood park, where he loves to play and explore. He is very curious and loves to chase after butterflies, but can be a little skittish around loud noises. If you see him or have any information on his whereabouts, please contact us as soon as possible. We miss him terribly and just want him to come home safely.",
  "He's a large orange tabby cat with bright yellow eyes, and is about 4 years old. He was last seen near our home in the urban area of town. Simba is very affectionate and loves to cuddle, but can be a bit skittish around loud noises.",
];

export const dogDescription = [
  "Our beloved pet has gone missing. He is a black and white Border Collie with a bright red collar. He is a friendly and energetic dog, and is always eager to play fetch. He went missing in the neighborhood around 5 PM yesterday, and we have not seen him since. He is microchipped and up to date on all his vaccinations. If anyone has seen dog or has any information about his whereabouts, please contact us immediately. We miss him terribly and are desperate to bring him back home where he belongs.",
];
